import Ticked from "assets/dashboard/Ticked.png";

export const customStyles = {
  option: (provided: any, state: any) => ({
    ...provided,
    background: state.isSelected && "#fff",
    position: "relative",
    color: "#1A2024",
    fontFamily: "Inter",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "1.4rem",
    lineHeight: "2.4rem",
    letterSpacing: "-0.006em",
    "&::after": {
      content: "''",
      display: state.isSelected ? "block" : "none",
      paddingRight: 15,
      backgroundImage: `url(${Ticked})`,
      backgroundRepeat: "no-repeat",
      position: "absolute",
      width: 14,
      height: 10,
      top: "50%",
      right: 0,
      transform: "translateY(-50%)",
    },
  }),
  control: (styles: any) => ({
    ...styles,
    width: "100%",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    paddingLeft: "1.5rem",
    border: "1px solid #DDE2E4",
    borderRadius: "0.6rem",
    cursor: "pointer",
  }),
  indicatorSeparator: () => ({
    display: "none",
  }),
  placeholder: () => ({
    fontFamily: "Inter",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "1.4rem",
    lineHeight: "2.4rem",
    letterSpacing: "-0.006em",
    color: "#9AA6AC",
  }),
  singleValue: () => ({
    fontFamily: "Inter",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "1.4rem",
    lineHeight: "2.4rem",
    letterSpacing: "-0.006em",
    color: "#1A2024",
  }),
  valueContainer: () => ({
    display: "flex",
    alignItems: "center",
  }),
};
