#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling and testing your project before committing...\n'

# Check ESLint Standards
npm run check-lint ||
(
        echo '\n😤🏀 ESLint check failed.
                Make the required changes listed above, add changes and try to commit again.'
        false;
)

# Check Prettier standards
npm run check-format ||
(
    echo '\n🤢🤮 Prettier check failed.
            Run yarn format, add changes and try commit again.'
    false;
)

# If everything passes... Now we can commit
echo '\n✅✅ You win this time... I am committing this now.\n'